// Product catalog: vibe templates, sticker packs, cursor presets and the
// music-library manifest. Seeded idempotently into the DB at every boot in
// EVERY environment — this is product content, not staging mock data.
// All artwork is original (inline SVG written here); all audio is
// generated by scripts/gen-audio.js (original, CC0).
'use strict';

// ------------------------------------------------------- doc builders

function section(id, background, minHeight, blocks) {
  return { id, background, minHeight, blocks };
}
function text(id, x, y, w, rotation, z, props) {
  return {
    id, type: 'text', x, y, w, rotation, z,
    props: Object.assign(
      { text: '', font: 'inter', size: 20, color: '#1F2B47', bold: false, align: 'left', style: 'none' },
      props
    ),
  };
}
function sticker(id, x, y, w, rotation, z, key) {
  return { id, type: 'sticker', x, y, w, rotation, z, props: { key } };
}
function widget(id, x, y, w, rotation, z, props) {
  return { id, type: 'widget', x, y, w, rotation, z, props };
}
function doc(cursor, song, footerStyle, sections) {
  return { version: 1, cursor, song, footerStyle, sections };
}
// Additive frame chrome on any block: 'window' | 'tape' | 'polaroid'.
function framed(block, frame, frameTitle) {
  block.frame = frame;
  if (frameTitle) block.frameTitle = frameTitle;
  return block;
}

// ------------------------------------------------------- vibe templates

// Flagship starter templates — featured on Home and the Templates gallery.
// Rule from the product brief: example content only; creation guidance
// lives in the editor UI (the `steps` checklist), never inside the page.
const FEATURED_TEMPLATES = [
  {
    key: 'scene-page', name: 'Scene Page',
    description: 'a cozy space to show off your world',
    tagline: 'Turn a real place into your page.',
    featured: true, subject_type: 'self',
    steps: [
      'Swap the background for a photo of your own space (🎨 → photo background)',
      'Update the status card with your day',
      'Nudge the furniture + widgets to fit your scene',
    ],
    content: doc(
      { type: 'preset', key: 'sparkle-wand' },
      { title: 'Cloud Garden', artist: 'MyPage originals (CC0)', linkUrl: null, source: 'library:cloud-garden' },
      { bg: '#5A4A38', color: '#F3E9DC' },
      [
        section('s1', { type: 'gradient', from: '#F3E9DC', to: '#E4D2B8', angle: 170 }, 660, [
          sticker('sc-win', 58, 34, 34, 0, 1, 'scene-window'),
          sticker('sc-poster', 7, 40, 20, -3, 1, 'scene-poster'),
          sticker('sc-shelf', 30, 66, 24, 0, 1, 'scene-shelf'),
          framed(widget('sc-song', 4, 128, 52, -1, 5, { kind: 'song' }), 'window', 'Now Playing'),
          framed(widget('sc-status', 52, 270, 44, 2, 5, { kind: 'status', title: 'status', emoji: '🪴', text: 'solo parenting today. wish me luck!' }), 'tape'),
          sticker('sc-plant', 3, 320, 18, 0, 2, 'scene-plant'),
          sticker('sc-sofa', 22, 356, 58, 0, 2, 'scene-sofa'),
          sticker('sc-book', 12, 520, 12, -6, 3, 'scene-book'),
          sticker('sc-phones', 68, 512, 14, 8, 3, 'scene-headphones'),
          widget('sc-mood', 34, 560, 40, -1, 4, { kind: 'mood', mood: '😌', label: 'grateful + inspired' }),
        ]),
        section('s2', { type: 'pattern', pattern: 'dots', color: '#FAF4E8', ink: '#E3D5BC' }, 560, [
          text('sc-t2', 8, 40, 80, -1, 2, { text: 'about this place', font: 'fraunces', size: 30, color: '#5A4A38', bold: true }),
          text('sc-t3', 10, 116, 74, 1, 2, { text: 'built from a real Sunday afternoon —\ntea going cold, records going warm.', font: 'typewriter', size: 16, color: '#8A7458' }),
          framed(widget('sc-album', 8, 230, 56, -2, 3, { kind: 'album', title: 'photo album', photos: [], layout: 'strip' }), 'polaroid', 'little moments'),
          widget('sc-gb', 8, 430, 84, 0, 1, { kind: 'guestbook', title: 'leave a note' }),
        ]),
      ]
    ),
  },
  {
    key: 'bestie-page', name: 'Bestie Page',
    description: 'celebrate your favorite person',
    tagline: 'A page for your favorite person.',
    featured: true, subject_type: 'friend',
    steps: [
      'Add your photos to the photo strip',
      'Set “our song” to your actual song (🎵 in the toolbar)',
      'Rewrite the memory + catchphrase in their words, then send it as a gift (⋯ menu)',
    ],
    content: doc(
      { type: 'preset', key: 'heart-wand' },
      { title: 'Dust & Sundays', artist: 'MyPage originals (CC0)', linkUrl: null, source: 'library:dust-and-sundays' },
      { bg: '#B03A7C', color: '#FFD9F2' },
      [
        section('s1', { type: 'gradient', from: '#FBF3E8', to: '#F2DFD0', angle: 165 }, 660, [
          text('bs-t1', 8, 38, 84, -2, 2, { text: 'ME & YOU', font: 'fraunces', size: 44, color: '#3D2B23', bold: true }),
          sticker('bs-spark', 78, 34, 14, 10, 3, 'bestie-sparkle'),
          sticker('bs-matcha', 12, 138, 22, -6, 3, 'bestie-matcha'),
          sticker('bs-coffee', 60, 138, 22, 5, 3, 'bestie-coffee'),
          sticker('bs-heart', 42, 210, 14, -8, 4, 'bestie-heart'),
          framed(widget('bs-song', 4, 320, 46, -1, 5, { kind: 'song', title: 'our song' }), 'window', 'our song'),
          framed(widget('bs-say', 52, 330, 44, 2, 5, { kind: 'quote', title: 'what you always say', text: '“it is what it is.”' }), 'tape'),
          widget('bs-mem', 8, 500, 82, -1, 4, { kind: 'quote', title: 'favorite memory', text: 'That road trip with no plan, all the snacks, and a playlist that fixed everything.' }),
        ]),
        section('s2', { type: 'pattern', pattern: 'stripes', color: '#FFF2F9', ink: '#F7D4E8', angle: 45 }, 620, [
          framed(widget('bs-strip', 8, 44, 52, -2, 3, { kind: 'album', title: 'photo strip', photos: [], layout: 'strip' }), 'polaroid', 'us, always'),
          widget('bs-pl', 38, 250, 58, 1, 4, { kind: 'playlist', title: 'gifted playlist', tracks: [
            { title: 'golden hour drive', artist: 'for windows down' },
            { title: 'the parking lot song', artist: 'ours' },
            { title: 'laughing until it hurts', artist: 'live version' },
            { title: 'see you soon', artist: 'always' },
          ] }),
          widget('bs-gb', 8, 470, 84, 0, 1, { kind: 'guestbook', title: 'notes for you' }),
        ]),
      ]
    ),
  },
  {
    key: 'y2k-page', name: 'Y2K Personal Page',
    description: 'glossy, nostalgic, and so you',
    tagline: 'Your own desktop-era corner.',
    featured: true, subject_type: 'self',
    steps: [
      'Make the lists yours — movies, eras, moods',
      'Rewrite the exit popup in your voice',
      'Add your photos, then set the song (🎵 in the toolbar)',
    ],
    content: doc(
      { type: 'preset', key: 'pixel-arrow' },
      { title: 'Starlight Arcade', artist: 'MyPage originals (CC0)', linkUrl: null, source: 'library:starlight-arcade' },
      { bg: '#D9DDE3', color: '#31384A' },
      [
        section('s1', { type: 'gradient', from: '#EBEDF1', to: '#C9CED8', angle: 180 }, 760, [
          text('yk-t1', 8, 34, 84, 0, 2, { text: 'MAIN CHARACTER MODE ✧', font: 'inter', size: 24, color: '#31384A', bold: true, style: 'shadow' }),
          sticker('yk-star', 82, 30, 12, 12, 3, 'y2k-star'),
          framed(widget('yk-song', 4, 110, 52, -1, 5, { kind: 'song' }), 'window', 'Now Playing'),
          framed(widget('yk-mov', 48, 268, 48, 1, 5, { kind: 'list', title: 'fave movies', items: [
            { label: 'Clueless', value: '1995' },
            { label: '10 Things I Hate About You', value: '1999' },
            { label: 'Legally Blonde', value: '2001' },
            { label: 'The Notebook', value: '2004' },
          ] }), 'window', 'Fave Movies'),
          sticker('yk-react', 5, 300, 34, -2, 4, 'y2k-reaction'),
          framed(widget('yk-era', 6, 508, 42, 0, 5, { kind: 'list', title: 'blog era', items: [
            { label: 'early 2000s', value: '✓' },
            { label: 'tumblr 2012', value: '' },
            { label: 'soft grunge', value: '' },
            { label: 'coastal', value: '' },
            { label: 'it-girl era', value: '' },
          ] }), 'window', 'blog era'),
          framed(widget('yk-pop', 46, 540, 50, 2, 6, { kind: 'popup', title: 'Are you sure you want to leave?', body: 'This page owner is probably overthinking, listening to music, and romanticizing her life. You’ll be back.', stayLabel: 'stay a while ♡', byeLabel: 'ok bye :(' }), 'window', 'system message'),
        ]),
        section('s2', { type: 'solid', color: '#F2F3F6' }, 440, [
          widget('yk-mq', 4, 40, 92, 0, 2, { kind: 'marquee', text: '☆ thanks for visiting my little corner of the web ☆', speed: 12, color: '#8A6FDF', size: 18 }),
          widget('yk-count', 12, 130, 60, 0, 2, { kind: 'counter', style: 'pink' }),
          widget('yk-gb', 8, 260, 84, 0, 1, { kind: 'guestbook' }),
        ]),
      ]
    ),
  },
  {
    key: 'pet-fan-page', name: 'Pet Fan Page',
    description: 'a fan page for your favorite little icon',
    tagline: 'For your favorite little icon.',
    featured: true, subject_type: 'pet',
    steps: [
      'Replace the portrait with your pet’s best photo',
      'Fill in the nicknames + snacks lists',
      'Retitle the fan club notes and share the page',
    ],
    content: doc(
      { type: 'preset', key: 'paw-prints' },
      { title: 'Paw Prints', artist: 'MyPage originals (CC0)', linkUrl: null, source: 'library:paw-prints' },
      { bg: '#31384A', color: '#DCE9F7' },
      [
        section('s1', { type: 'gradient', from: '#DCE9F7', to: '#F7EFDC', angle: 165 }, 700, [
          text('pt-t1', 8, 34, 84, 0, 2, { text: 'THE ICON.', font: 'fraunces', size: 46, color: '#1F2B47', bold: true }),
          text('pt-t2', 8, 132, 72, 0, 2, { text: 'the city’s most influential good pet', font: 'typewriter', size: 15, color: '#5A6B8C' }),
          sticker('pt-portrait', 50, 176, 46, 2, 3, 'pet-portrait'),
          framed(widget('pt-mood', 4, 196, 44, -2, 5, { kind: 'status', title: 'current mood', emoji: '😎', text: 'unbothered. moisturized. in my lane.' }), 'tape'),
          widget('pt-names', 5, 380, 42, -1, 4, { kind: 'list', title: 'nicknames', items: [
            { label: 'Beans', value: '' },
            { label: 'Sir Snacksalot', value: '' },
            { label: 'The Baron', value: '' },
            { label: 'Bug', value: '' },
          ] }),
          widget('pt-snacks', 52, 500, 44, 1, 4, { kind: 'list', title: 'favorite snacks', items: [
            { label: 'cheese tax', value: 'daily' },
            { label: 'one (1) blueberry', value: 'rare' },
            { label: 'whatever you’re having', value: 'always' },
          ] }),
          sticker('pt-paw', 84, 130, 12, -10, 3, 'pet-paw'),
        ]),
        section('s2', { type: 'pattern', pattern: 'dots', color: '#FBF6EC', ink: '#EADFC8' }, 640, [
          framed(widget('pt-ootd', 8, 44, 58, -1, 3, { kind: 'album', title: 'outfit of the day', photos: [], layout: 'grid' }), 'polaroid', 'lewks'),
          widget('pt-funny', 34, 320, 60, 1, 4, { kind: 'quote', title: 'funniest moment', text: 'Barked at his own reflection for ten minutes, then befriended it.' }),
          widget('pt-count', 8, 460, 52, 0, 2, { kind: 'counter', style: 'classic' }),
          widget('pt-gb', 6, 570, 88, 0, 1, { kind: 'guestbook', title: 'fan club notes' }),
        ]),
      ]
    ),
  },
];

// Restyle-only vibes: full looks you can start from or re-skin with.
const STYLE_TEMPLATES = [
  {
    key: 'y2k', name: 'Y2K glitter', description: 'hot pink, sparkle text, everything shiny',
    content: doc({ type: 'preset', key: 'heart-wand' }, null, { bg: '#FF9DE2', color: '#2A1F3D' }, [
      section('s1', { type: 'gradient', from: '#FF9DE2', to: '#8A6FDF', angle: 150 }, 520, [
        text('t1', 6, 44, 88, -3, 3, { text: '☆ ur page here ☆', font: 'fraunces', size: 40, color: '#FFFFFF', bold: true, style: 'sparkle' }),
        widget('m1', 4, 170, 92, 0, 2, { kind: 'marquee', text: '♡ welcome 2 my corner ♡ sign the guestbook ♡', speed: 10, color: '#FFE93F', size: 20 }),
        sticker('st1', 74, 250, 18, 14, 4, 'blink-star'),
        widget('w1', 10, 300, 60, -2, 2, { kind: 'mood', mood: '💅', label: 'iconic' }),
        sticker('st2', 6, 380, 15, -10, 4, 'blink-heart'),
      ]),
      section('s2', { type: 'pattern', pattern: 'checker', color: '#FFD9F2', ink: '#FF9DE2' }, 420, [
        text('t2', 8, 40, 80, 1, 2, { text: 'about me\n(everything, all at once)', font: 'comic', size: 24, color: '#B03A7C', bold: true }),
        widget('w2', 10, 190, 78, 0, 2, { kind: 'counter', style: 'pink' }),
        widget('w3', 8, 300, 84, 0, 1, { kind: 'guestbook' }),
      ]),
    ]),
  },
  {
    key: 'scene2007', name: '2007 scene', description: 'dark checkers, rainbow text, rawr',
    content: doc({ type: 'preset', key: 'tiny-sword' }, null, { bg: '#101014', color: '#E8DCFF' }, [
      section('s1', { type: 'pattern', pattern: 'checker', color: '#121218', ink: '#232330' }, 540, [
        text('t1', 6, 44, 88, -4, 3, { text: 'xX_yourname_Xx', font: 'comic', size: 38, color: '#FF5ECB', bold: true, style: 'rainbow' }),
        widget('m1', 4, 168, 92, 0, 2, { kind: 'marquee', text: '~*~ rawr means i love u in dinosaur ~*~', speed: 8, color: '#7CFCD0', size: 18 }),
        sticker('st1', 76, 240, 16, 12, 4, 'blink-bolt'),
        text('t2', 10, 310, 70, 2, 2, { text: 'music is my life.\nthe scene is not dead.', font: 'typewriter', size: 18, color: '#9DB4CC' }),
      ]),
      section('s2', { type: 'solid', color: '#0C0C10' }, 420, [
        widget('w1', 10, 50, 80, 0, 2, { kind: 'links', links: [{ label: 'my band', url: 'https://example.com' }, { label: 'art blog', url: 'https://example.com' }] }),
        widget('w2', 8, 280, 84, 0, 1, { kind: 'guestbook' }),
      ]),
    ]),
  },
  {
    key: 'cottagecore', name: 'cottagecore', description: 'soft paper, pressed flowers, a warm kettle',
    content: doc({ type: 'preset', key: 'paw-prints' }, null, { bg: '#F3EDDF', color: '#5A6378' }, [
      section('s1', { type: 'pattern', pattern: 'dots', color: '#F6F1E3', ink: '#DCE7D2' }, 520, [
        text('t1', 8, 48, 84, -2, 3, { text: 'a soft little corner', font: 'hand', size: 42, color: '#6B7B4E', bold: false }),
        sticker('st1', 72, 150, 18, 8, 4, 'stamp-mushroom'),
        text('t2', 10, 220, 66, 1, 2, { text: 'tea steeping · bread rising ·\nnowhere to be', font: 'typewriter', size: 17, color: '#8A5A2B' }),
        widget('w1', 10, 360, 70, -1, 2, { kind: 'currently', items: [{ verb: 'reading', what: 'a battered paperback' }, { verb: 'growing', what: 'basil, hopefully' }] }),
      ]),
      section('s2', { type: 'gradient', from: '#EFE9D8', to: '#DCE7D2', angle: 180 }, 380, [
        sticker('st2', 8, 60, 16, -6, 3, 'stamp-flower'),
        text('t3', 30, 90, 58, 0, 2, { text: '“the ordinary devotions are enough.”', font: 'fraunces', size: 20, color: '#5A6378' }),
        widget('w2', 10, 240, 78, 0, 1, { kind: 'counter', style: 'classic' }),
      ]),
    ]),
  },
  {
    key: 'dreamcore', name: 'dreamcore', description: 'somewhere you half-remember',
    content: doc({ type: 'preset', key: 'ghost' }, null, { bg: '#1A1430', color: '#B3A6E8' }, [
      section('s1', { type: 'gradient', from: '#1A1430', to: '#2E5B6E', angle: 200 }, 560, [
        text('t1', 8, 60, 84, -1, 3, { text: 'you have been here before', font: 'inter', size: 32, color: '#CFF6FF', bold: true, style: 'outline' }),
        widget('m1', 4, 200, 92, 0, 2, { kind: 'marquee', text: 'the pool is closed · the hallway hums · it is always 3pm', speed: 16, color: '#8A6FDF', size: 16 }),
        widget('w1', 14, 300, 56, 2, 2, { kind: 'mood', mood: '🌙', label: 'liminal' }),
        sticker('st1', 70, 400, 18, -8, 3, 'blink-moon'),
      ]),
      section('s2', { type: 'solid', color: '#121022' }, 380, [
        text('t2', 12, 70, 70, 0, 2, { text: 'leave a note.\nprove you were real.', font: 'typewriter', size: 17, color: '#8FA6B8' }),
        widget('w2', 8, 200, 84, 0, 1, { kind: 'guestbook' }),
      ]),
    ]),
  },
  {
    key: 'vaporwave', name: 'vaporwave', description: 'sunset gradients, pixel serif, checkerboard floors',
    content: doc({ type: 'preset', key: 'hourglass' }, { title: 'n e o n r a i n', artist: 'MyPage originals', linkUrl: null, source: 'library:neon-rain' }, { bg: '#2A1F3D', color: '#FF9DE2' }, [
      section('s1', { type: 'gradient', from: '#FF6B57', to: '#8A6FDF', angle: 180 }, 540, [
        text('t1', 6, 50, 88, 0, 3, { text: 'ＡＥＳＴＨＥＴＩＣ', font: 'pixel', size: 26, color: '#FFFFFF', style: 'shadow' }),
        widget('sg1', 10, 170, 80, -2, 3, { kind: 'song' }),
        sticker('st1', 72, 330, 18, 10, 3, 'stamp-planet'),
        text('t2', 10, 400, 70, 0, 2, { text: 'mall fountains · dial tones · forever dusk', font: 'inter', size: 15, color: '#FFD9F2' }),
      ]),
      section('s2', { type: 'pattern', pattern: 'checker', color: '#2A1F3D', ink: '#3D2E58' }, 360, [
        widget('w1', 12, 60, 74, 0, 2, { kind: 'counter', style: 'terminal' }),
        widget('w2', 8, 190, 84, 0, 1, { kind: 'guestbook' }),
      ]),
    ]),
  },
  {
    key: 'scrapbook', name: 'scrapbook / journal', description: 'taped corners, typewriter notes, hoarded scraps',
    content: doc({ type: 'preset', key: 'sparkle-wand' }, null, { bg: '#FAF6EE', color: '#8A5A2B' }, [
      section('s1', { type: 'solid', color: '#FAF6EE' }, 560, [
        text('t1', 8, 44, 80, -2, 3, { text: 'things i am keeping', font: 'fraunces', size: 34, color: '#1F2B47', bold: true }),
        text('t2', 12, 150, 62, 3, 2, { text: '“Tell me, what is it you plan to do\nwith your one wild and precious life?”', font: 'typewriter', size: 16, color: '#5A6378' }),
        sticker('st1', 70, 130, 20, -7, 4, 'stamp-heart'),
        text('t3', 16, 300, 58, -4, 2, { text: 'ticket stubs · pressed leaves ·\nthe good kind of quiet', font: 'hand', size: 24, color: '#B03A7C' }),
        sticker('st2', 8, 420, 15, 9, 3, 'stamp-strawberry'),
      ]),
      section('s2', { type: 'pattern', pattern: 'grid', color: '#FFFDF4', ink: '#F0E6C8' }, 380, [
        widget('w1', 10, 50, 76, -1, 2, { kind: 'currently', items: [{ verb: 'reading', what: '…' }, { verb: 'watching', what: '…' }, { verb: 'playing', what: '…' }] }),
        widget('w2', 12, 260, 70, 0, 1, { kind: 'counter', style: 'classic' }),
      ]),
    ]),
  },
  {
    key: 'terminal', name: 'brutalist terminal', description: 'green phosphor, no decoration except the decoration',
    content: doc({ type: 'preset', key: 'pixel-arrow' }, null, { bg: '#0A0F0A', color: '#57D93E' }, [
      section('s1', { type: 'pattern', pattern: 'grid', color: '#0A0F0A', ink: '#12240F' }, 540, [
        text('t1', 6, 44, 88, 0, 3, { text: '> whoami', font: 'pixel', size: 20, color: '#57D93E' }),
        text('t2', 6, 130, 88, 0, 2, { text: 'guest@mypage:~$ a page.\nno tracking. no feed. no ads.\njust bytes arranged with intent.', font: 'typewriter', size: 16, color: '#9FE8D2' }),
        widget('w1', 6, 320, 80, 0, 2, { kind: 'links', links: [{ label: '~/projects', url: 'https://example.com' }, { label: '~/writing', url: 'https://example.com' }] }),
      ]),
      section('s2', { type: 'solid', color: '#060906' }, 340, [
        widget('w2', 8, 50, 76, 0, 2, { kind: 'counter', style: 'terminal' }),
        widget('w3', 6, 180, 88, 0, 1, { kind: 'guestbook' }),
      ]),
    ]),
  },
  {
    key: 'construction', name: 'under construction', description: 'the eternal retro-web promise',
    content: doc({ type: 'preset', key: 'hourglass' }, null, { bg: '#FFE93F', color: '#1F2B47' }, [
      section('s1', { type: 'pattern', pattern: 'stripes', color: '#FFE93F', ink: '#1F2B47', angle: 45 }, 520, [
        text('t1', 8, 50, 84, -2, 3, { text: '🚧 UNDER CONSTRUCTION 🚧', font: 'pixel', size: 20, color: '#1F2B47', bold: true }),
        widget('m1', 4, 160, 92, 0, 2, { kind: 'marquee', text: 'pardon our dust — this page is forever becoming', speed: 9, color: '#1F2B47', size: 18 }),
        sticker('st1', 12, 260, 34, -4, 3, 'badge-construction'),
        sticker('st2', 54, 300, 34, 5, 3, 'badge-new'),
      ]),
      section('s2', { type: 'solid', color: '#FFFDF4' }, 400, [
        sticker('st3', 8, 50, 34, -3, 3, 'badge-noalgo'),
        sticker('st4', 52, 80, 34, 4, 3, 'badge-heart'),
        widget('w1', 12, 200, 70, 0, 2, { kind: 'counter', style: 'classic' }),
        widget('w2', 8, 320, 84, 0, 1, { kind: 'guestbook' }),
      ]),
    ]),
  },
];

// Featured first so fresh installs get flagship ids 1–4; on existing DBs
// the upsert keys by `key` and the client orders by `featured` anyway.
const TEMPLATES = FEATURED_TEMPLATES.concat(
  STYLE_TEMPLATES.map((t) => Object.assign({ featured: false, subject_type: null, tagline: null, steps: null }, t))
);

// ------------------------------------------------------- sticker packs

// Original inline SVGs. Square packs use viewBox 0 0 100 100; badges use
// the classic 88×31 web-button proportions (0 0 176 62); scene furniture
// uses whatever box fits the object.
const s = (body, vb = '0 0 100 100') => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb}">${body}</svg>`;
const STAMP_FRAME = '<rect x="4" y="4" width="92" height="92" fill="#FFFDF4" stroke="#D6C9A8" stroke-width="3" stroke-dasharray="7 5"/>';
const BADGE = (bg, stroke) => `<rect x="2" y="2" width="172" height="58" rx="6" fill="${bg}" stroke="${stroke}" stroke-width="4"/>`;

const STICKER_PACKS = [
  {
    key: 'blinkies', name: 'blinkies',
    stickers: [
      { key: 'blink-star', svg: s('<path d="M50 6 61 38 95 38 68 58 78 92 50 71 22 92 32 58 5 38 39 38Z" fill="#FFE93F" stroke="#C9A227" stroke-width="4"/><circle cx="50" cy="50" r="7" fill="#FFFDF4"/>') },
      { key: 'blink-heart', svg: s('<path d="M50 88 14 52C2 40 6 18 24 14c12-3 22 4 26 12 4-8 14-15 26-12 18 4 22 26 10 38Z" fill="#FF5ECB" stroke="#B03A7C" stroke-width="4"/><circle cx="36" cy="34" r="6" fill="#FFD9F2"/>') },
      { key: 'blink-moon', svg: s('<path d="M66 8A44 44 0 1 0 92 66 36 36 0 0 1 66 8Z" fill="#B3A6E8" stroke="#8A6FDF" stroke-width="4"/><circle cx="30" cy="30" r="4" fill="#FFFDF4"/><circle cx="20" cy="52" r="3" fill="#FFFDF4"/>') },
      { key: 'blink-bolt', svg: s('<path d="M58 4 20 56h20L42 96 80 42H58Z" fill="#7CFCD0" stroke="#2E9E8F" stroke-width="4"/>') },
      { key: 'blink-flower', svg: s('<g fill="#FF9DE2" stroke="#B03A7C" stroke-width="3"><circle cx="50" cy="22" r="15"/><circle cx="78" cy="42" r="15"/><circle cx="67" cy="74" r="15"/><circle cx="33" cy="74" r="15"/><circle cx="22" cy="42" r="15"/></g><circle cx="50" cy="50" r="14" fill="#FFE93F" stroke="#C9A227" stroke-width="3"/>') },
      { key: 'blink-butterfly', svg: s('<g stroke="#8A6FDF" stroke-width="3"><path d="M50 50C20 10 4 24 12 44c6 14 26 16 38 6Z" fill="#B3A6E8"/><path d="M50 50c30-40 46-26 38-6-6 14-26 16-38 6Z" fill="#B3A6E8"/><path d="M50 52C22 88 6 76 14 58c6-12 24-14 36-6Z" fill="#FF9DE2"/><path d="M50 52c28 36 44 24 36 6-6-12-24-14-36-6Z" fill="#FF9DE2"/></g><rect x="46" y="30" width="8" height="42" rx="4" fill="#2A1F3D"/>') },
    ],
  },
  {
    key: 'stamps', name: 'stamps',
    stickers: [
      { key: 'stamp-heart', svg: s(STAMP_FRAME + '<path d="M50 76 26 52c-8-8-5-22 7-25 8-2 14 3 17 8 3-5 9-10 17-8 12 3 15 17 7 25Z" fill="#D65A9E"/>') },
      { key: 'stamp-mushroom', svg: s(STAMP_FRAME + '<path d="M20 50c0-20 14-32 30-32s30 12 30 32Z" fill="#FF6B57"/><circle cx="36" cy="34" r="5" fill="#FFFDF4"/><circle cx="58" cy="28" r="4" fill="#FFFDF4"/><rect x="40" y="50" width="20" height="28" rx="8" fill="#F3EDDF" stroke="#D6C9A8" stroke-width="2"/>') },
      { key: 'stamp-cat', svg: s(STAMP_FRAME + '<path d="M28 40 24 20l14 8Zm44 0 4-20-14 8Z" fill="#8A5A2B"/><circle cx="50" cy="52" r="26" fill="#C9A227"/><circle cx="41" cy="47" r="3.5" fill="#1F2B47"/><circle cx="59" cy="47" r="3.5" fill="#1F2B47"/><path d="M44 60q6 6 12 0" stroke="#1F2B47" stroke-width="3" fill="none"/>') },
      { key: 'stamp-planet', svg: s(STAMP_FRAME + '<circle cx="50" cy="50" r="22" fill="#8A6FDF"/><ellipse cx="50" cy="52" rx="38" ry="10" fill="none" stroke="#FF9DE2" stroke-width="4"/><circle cx="42" cy="43" r="5" fill="#B3A6E8"/>') },
      { key: 'stamp-flower', svg: s(STAMP_FRAME + '<g fill="#7FB542"><rect x="47" y="54" width="6" height="26"/></g><g fill="#FF9DE2" stroke="#B03A7C" stroke-width="2"><circle cx="50" cy="26" r="9"/><circle cx="66" cy="36" r="9"/><circle cx="62" cy="52" r="9"/><circle cx="38" cy="52" r="9"/><circle cx="34" cy="36" r="9"/></g><circle cx="50" cy="40" r="8" fill="#FFE93F"/>') },
      { key: 'stamp-strawberry', svg: s(STAMP_FRAME + '<path d="M50 82C30 70 24 52 30 40c6-10 34-10 40 0 6 12 0 30-20 42Z" fill="#FF6B57"/><path d="M38 32c4-8 20-8 24 0l-12 8Z" fill="#7FB542"/><g fill="#FFFDF4"><circle cx="42" cy="50" r="2"/><circle cx="56" cy="48" r="2"/><circle cx="50" cy="62" r="2"/></g>') },
    ],
  },
  {
    key: 'badges', name: 'retro-web badges',
    stickers: [
      { key: 'badge-new', svg: s(BADGE('#1F2B47', '#FFE93F') + '<text x="88" y="42" font-family="monospace" font-size="30" font-weight="bold" fill="#FFE93F" text-anchor="middle">NEW!!</text>', '0 0 176 62') },
      { key: 'badge-construction', svg: s(BADGE('#FFE93F', '#1F2B47') + '<text x="88" y="27" font-family="monospace" font-size="16" font-weight="bold" fill="#1F2B47" text-anchor="middle">🚧 UNDER</text><text x="88" y="49" font-family="monospace" font-size="16" font-weight="bold" fill="#1F2B47" text-anchor="middle">CONSTRUCTION</text>', '0 0 176 62') },
      { key: 'badge-noalgo', svg: s(BADGE('#0A0F0A', '#57D93E') + '<text x="88" y="27" font-family="monospace" font-size="15" fill="#57D93E" text-anchor="middle">100% ALGORITHM</text><text x="88" y="49" font-family="monospace" font-size="15" fill="#57D93E" text-anchor="middle">FREE ZONE</text>', '0 0 176 62') },
      { key: 'badge-heart', svg: s(BADGE('#FFD9F2', '#D65A9E') + '<text x="88" y="40" font-family="monospace" font-size="18" font-weight="bold" fill="#B03A7C" text-anchor="middle">made with ♥</text>', '0 0 176 62') },
      { key: 'badge-guestbook', svg: s(BADGE('#2A1F3D', '#B3A6E8') + '<text x="88" y="40" font-family="monospace" font-size="16" font-weight="bold" fill="#B3A6E8" text-anchor="middle">SIGN MY BOOK</text>', '0 0 176 62') },
      { key: 'badge-bestviewed', svg: s(BADGE('#F3EDDF', '#8A5A2B') + '<text x="88" y="27" font-family="monospace" font-size="14" fill="#8A5A2B" text-anchor="middle">best viewed</text><text x="88" y="49" font-family="monospace" font-size="14" fill="#8A5A2B" text-anchor="middle">curled up in bed</text>', '0 0 176 62') },
    ],
  },
  {
    key: 'scene', name: 'scene stuff',
    stickers: [
      { key: 'scene-sofa', svg: s('<rect x="6" y="34" width="20" height="52" rx="9" fill="#C7AE8C"/><rect x="174" y="34" width="20" height="52" rx="9" fill="#C7AE8C"/><rect x="14" y="52" width="172" height="34" rx="10" fill="#D9C6A8"/><rect x="24" y="26" width="74" height="34" rx="10" fill="#E8D9BD" stroke="#C7AE8C" stroke-width="2"/><rect x="102" y="26" width="74" height="34" rx="10" fill="#E8D9BD" stroke="#C7AE8C" stroke-width="2"/><rect x="52" y="40" width="34" height="24" rx="6" transform="rotate(-8 69 52)" fill="#A9BF8E"/><rect x="116" y="40" width="34" height="24" rx="6" transform="rotate(6 133 52)" fill="#D98E7A"/><rect x="26" y="86" width="8" height="10" fill="#8A6B4A"/><rect x="166" y="86" width="8" height="10" fill="#8A6B4A"/>', '0 0 200 100') },
      { key: 'scene-plant', svg: s('<path d="M50 62C46 40 30 32 18 34c4 16 18 24 30 28Z" fill="#6B8F4E"/><path d="M50 62c4-24 20-34 32-32-4 18-18 28-32 32Z" fill="#7FA55C"/><path d="M50 64c0-18 2-32 0-44" stroke="#5A7A40" stroke-width="4" fill="none"/><path d="M32 64h36l-5 30H37Z" fill="#C97B5A"/><rect x="29" y="60" width="42" height="8" rx="3" fill="#B5684A"/>') },
      { key: 'scene-window', svg: s('<rect x="6" y="6" width="108" height="88" rx="6" fill="#E8D9BD" stroke="#C7AE8C" stroke-width="4"/><rect x="14" y="14" width="92" height="72" fill="#BBD8E8"/><path d="M14 66c14-10 26-4 36 2 12 7 26 8 40-2l16-10v30H14Z" fill="#A9C8A0"/><circle cx="88" cy="30" r="9" fill="#FFF3C4"/><rect x="58" y="14" width="4" height="72" fill="#C7AE8C"/><rect x="14" y="48" width="92" height="4" fill="#C7AE8C"/>', '0 0 120 100') },
      { key: 'scene-shelf', svg: s('<rect x="4" y="60" width="112" height="8" rx="3" fill="#8A6B4A"/><rect x="12" y="26" width="10" height="34" fill="#D98E7A"/><rect x="24" y="20" width="10" height="40" fill="#A9BF8E"/><rect x="36" y="30" width="9" height="30" fill="#7A9BB5"/><rect x="47" y="24" width="10" height="36" transform="rotate(8 52 42)" fill="#C9A227"/><ellipse cx="78" cy="46" rx="14" ry="14" fill="#E8D9BD" stroke="#C7AE8C" stroke-width="3"/><circle cx="78" cy="46" r="5" fill="#5A4A38"/><path d="M98 60c0-10 4-16 10-18" stroke="#6B8F4E" stroke-width="3" fill="none"/>', '0 0 120 76') },
      { key: 'scene-poster', svg: s('<rect x="6" y="6" width="88" height="118" fill="#FFFDF4" stroke="#5A4A38" stroke-width="4"/><rect x="16" y="16" width="68" height="70" fill="#BBD8E8"/><path d="M16 66l18-20 14 14 12-22 24 28v20H16Z" fill="#6B8F4E"/><circle cx="70" cy="32" r="7" fill="#FFF3C4"/><text x="50" y="108" font-family="monospace" font-size="11" fill="#5A4A38" text-anchor="middle">someplace</text>', '0 0 100 130') },
      { key: 'scene-headphones', svg: s('<path d="M20 58C20 34 33 20 50 20s30 14 30 38" stroke="#3D3A45" stroke-width="7" fill="none"/><rect x="12" y="54" width="16" height="28" rx="7" fill="#3D3A45"/><rect x="72" y="54" width="16" height="28" rx="7" fill="#3D3A45"/><rect x="15" y="58" width="10" height="20" rx="4" fill="#D98E7A"/><rect x="75" y="58" width="10" height="20" rx="4" fill="#D98E7A"/>') },
      { key: 'scene-book', svg: s('<path d="M14 22c22-8 32-8 36 0v58c-4-8-14-8-36 0Z" fill="#D98E7A" stroke="#B56A54" stroke-width="3"/><path d="M86 22c-22-8-32-8-36 0v58c4-8 14-8 36 0Z" fill="#E8D9BD" stroke="#C7AE8C" stroke-width="3"/><path d="M58 34h20M58 44h20M58 54h14" stroke="#B59C77" stroke-width="3"/>') },
    ],
  },
  {
    key: 'bestie', name: 'bestie kit',
    stickers: [
      { key: 'bestie-matcha', svg: s('<path d="M30 26h40l-6 62H36Z" fill="#D7ECC9" stroke="#8FBF6E" stroke-width="3"/><path d="M32 40h36l-4 44H36Z" fill="#A9D68B"/><g fill="#EAF6DF" stroke="#8FBF6E" stroke-width="2"><rect x="38" y="46" width="10" height="10" rx="2" transform="rotate(-8 43 51)"/><rect x="52" y="52" width="10" height="10" rx="2" transform="rotate(10 57 57)"/><rect x="42" y="66" width="10" height="10" rx="2" transform="rotate(4 47 71)"/></g><rect x="28" y="20" width="44" height="8" rx="4" fill="#FFFDF4" stroke="#8FBF6E" stroke-width="2"/><rect x="56" y="2" width="6" height="26" rx="3" transform="rotate(12 59 15)" fill="#D65A9E"/>') },
      { key: 'bestie-coffee', svg: s('<path d="M30 26h40l-6 62H36Z" fill="#EAD9C4" stroke="#B58A5C" stroke-width="3"/><path d="M32 40h36l-4 44H36Z" fill="#C89B66"/><path d="M32 40h36l-1 12H33Z" fill="#E6CDA8"/><g fill="#F4E7D3" stroke="#B58A5C" stroke-width="2"><rect x="39" y="50" width="10" height="10" rx="2" transform="rotate(-10 44 55)"/><rect x="52" y="58" width="10" height="10" rx="2" transform="rotate(8 57 63)"/><rect x="42" y="70" width="9" height="9" rx="2" transform="rotate(-4 46 74)"/></g><rect x="28" y="20" width="44" height="8" rx="4" fill="#FFFDF4" stroke="#B58A5C" stroke-width="2"/><rect x="40" y="2" width="6" height="26" rx="3" transform="rotate(-10 43 15)" fill="#8A6FDF"/>') },
      { key: 'bestie-heart', svg: s('<path d="M50 84C24 64 14 48 20 34c5-11 20-12 28-2 2 3 3 3 5 0 8-10 23-9 28 2 6 14-5 30-31 50Z" fill="none" stroke="#D65A9E" stroke-width="5" stroke-linecap="round" stroke-dasharray="1 9"/><path d="M50 78C28 60 20 47 25 36c4-9 16-9 22-1 2 3 4 3 6 0 6-8 18-8 22 1 5 11-3 24-25 42Z" fill="#FF9DE2" opacity=".85"/>') },
      { key: 'bestie-strip', svg: s('<rect x="4" y="4" width="72" height="192" rx="4" fill="#FFFDF4" stroke="#3D3A45" stroke-width="4"/><g fill="#D8E4EE" stroke="#9FB2C4" stroke-width="2"><rect x="12" y="14" width="56" height="50"/><rect x="12" y="74" width="56" height="50"/><rect x="12" y="134" width="56" height="50"/></g><g fill="#8FA6B8"><circle cx="30" cy="34" r="7"/><circle cx="50" cy="94" r="7"/><circle cx="34" cy="158" r="7"/></g><path d="M20 52c8-8 16-8 24 0M38 112c8-8 16-8 24 0M22 172c8-8 16-8 24 0" stroke="#8FA6B8" stroke-width="3" fill="none"/>', '0 0 80 200') },
      { key: 'bestie-sparkle', svg: s('<path d="M50 8c4 18 10 24 28 28-18 4-24 10-28 28-4-18-10-24-28-28 18-4 24-10 28-28Z" fill="#FFE93F" stroke="#C9A227" stroke-width="3"/><path d="M78 58c2 9 5 12 14 14-9 2-12 5-14 14-2-9-5-12-14-14 9-2 12-5 14-14Z" fill="#FF9DE2" stroke="#B03A7C" stroke-width="2.5"/>') },
    ],
  },
  {
    key: 'y2k-pet', name: 'y2k & pets',
    stickers: [
      { key: 'y2k-star', svg: s('<defs><linearGradient id="chrome" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#F4F6FA"/><stop offset=".5" stop-color="#AEB6C6"/><stop offset="1" stop-color="#E6EAF2"/></linearGradient></defs><path d="M50 4c6 26 14 34 42 46-28 12-36 20-42 46-6-26-14-34-42-46C36 38 44 30 50 4Z" fill="url(#chrome)" stroke="#7C8598" stroke-width="3"/><circle cx="50" cy="50" r="7" fill="#FFFFFF"/>') },
      { key: 'y2k-cursor', svg: s('<path d="M30 12 76 54 50 56l14 26-12 6-14-27-18 19Z" fill="#FFFFFF" stroke="#31384A" stroke-width="5" stroke-linejoin="round"/>') },
      { key: 'y2k-reaction', svg: s('<rect x="3" y="3" width="154" height="118" rx="8" fill="#F6F7F9" stroke="#8A93A6" stroke-width="3"/><rect x="3" y="3" width="154" height="22" rx="8" fill="#DEE2EA"/><circle cx="16" cy="14" r="4" fill="#FF6B57"/><circle cx="28" cy="14" r="4" fill="#FFE93F"/><circle cx="40" cy="14" r="4" fill="#7FB542"/><rect x="16" y="34" width="80" height="70" rx="4" fill="#E8E2D4"/><circle cx="56" cy="60" r="16" fill="#EFC9A8"/><path d="M42 56h12v7H42Zm16 0h12v7H58Z" fill="#31384A"/><path d="M54 56h8" stroke="#31384A" stroke-width="3"/><path d="M48 74q8 6 16 0" stroke="#8A6B4A" stroke-width="3" fill="none"/><rect x="40" y="84" width="32" height="20" rx="4" fill="#5A6B8C"/><text x="126" y="60" font-family="monospace" font-size="11" fill="#31384A" text-anchor="middle">current</text><text x="126" y="76" font-family="monospace" font-size="11" fill="#31384A" text-anchor="middle">mood ↑</text>', '0 0 160 124') },
      { key: 'pet-paw', svg: s('<circle cx="50" cy="50" r="44" fill="#FFE93F" stroke="#C9A227" stroke-width="4"/><g fill="#31384A"><ellipse cx="34" cy="36" rx="7" ry="9"/><ellipse cx="50" cy="30" rx="7" ry="9"/><ellipse cx="66" cy="36" rx="7" ry="9"/><path d="M50 44c12 0 20 8 20 17 0 8-8 13-20 13s-20-5-20-13c0-9 8-17 20-17Z"/></g>') },
      { key: 'pet-portrait', svg: s('<defs><linearGradient id="citysky" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#9DBFE8"/><stop offset="1" stop-color="#D8E6F4"/></linearGradient></defs><rect x="4" y="4" width="112" height="142" rx="6" fill="url(#citysky)" stroke="#FFFDF4" stroke-width="8"/><g fill="#B9C6D6"><rect x="10" y="42" width="20" height="104"/><rect x="90" y="30" width="22" height="116"/><rect x="34" y="58" width="14" height="88"/></g><g fill="#8FA2B8"><rect x="13" y="48" width="4" height="6"/><rect x="21" y="48" width="4" height="6"/><rect x="13" y="60" width="4" height="6"/><rect x="94" y="38" width="5" height="7"/><rect x="102" y="38" width="5" height="7"/><rect x="94" y="52" width="5" height="7"/></g><ellipse cx="62" cy="118" rx="26" ry="30" fill="#C99B66"/><path d="M40 96c-6 26 2 40 8 46h28c6-6 14-20 8-46Z" fill="#E3D3BD"/><circle cx="62" cy="86" r="24" fill="#C99B66"/><path d="M40 78c-8 4-10 26-4 34 6-2 10-10 10-18Z" fill="#A97B4E"/><path d="M84 78c8 4 10 26 4 34-6-2-10-10-10-18Z" fill="#A97B4E"/><path d="M40 74c2-12 12-20 22-20s20 8 22 20c-6 6-38 6-44 0Z" fill="#E8E2D4"/><rect x="40" y="80" width="20" height="12" rx="6" fill="#FF8A3D" stroke="#D96A20" stroke-width="2"/><rect x="64" y="80" width="20" height="12" rx="6" fill="#FF8A3D" stroke="#D96A20" stroke-width="2"/><path d="M60 86h4" stroke="#D96A20" stroke-width="3"/><ellipse cx="62" cy="102" rx="6" ry="4" fill="#31384A"/><path d="M62 106v6" stroke="#31384A" stroke-width="2"/>', '0 0 120 150') },
    ],
  },
];

// ------------------------------------------------------- cursor presets

const CURSOR_PRESETS = [
  { key: 'sparkle-wand', name: 'sparkle wand', config: { emoji: '✨', trail: 'sparkle' } },
  { key: 'tiny-sword', name: 'tiny sword', config: { emoji: '🗡️', trail: null } },
  { key: 'paw-prints', name: 'paw prints', config: { emoji: '🐾', trail: 'paws' } },
  { key: 'heart-wand', name: 'heart wand', config: { emoji: '💖', trail: 'hearts' } },
  { key: 'hourglass', name: 'retro hourglass', config: { emoji: '⌛', trail: null } },
  { key: 'ghost', name: 'little ghost', config: { emoji: '👻', trail: 'sparkle' } },
  { key: 'pixel-arrow', name: 'pixel arrow', config: { emoji: '↖️', trail: null } },
  { key: 'strawberry', name: 'strawberry', config: { emoji: '🍓', trail: null } },
];

// ------------------------------------------------------- music library

const MUSIC_LIBRARY = [
  { key: 'dust-and-sundays', title: 'Dust & Sundays', artist: 'MyPage originals (CC0)', file_path: '/audio/library/dust-and-sundays.wav', style: 'lofi' },
  { key: 'starlight-arcade', title: 'Starlight Arcade', artist: 'MyPage originals (CC0)', file_path: '/audio/library/starlight-arcade.wav', style: 'chiptune' },
  { key: 'cloud-garden', title: 'Cloud Garden', artist: 'MyPage originals (CC0)', file_path: '/audio/library/cloud-garden.wav', style: 'ambient' },
  { key: 'paw-prints', title: 'Paw Prints', artist: 'MyPage originals (CC0)', file_path: '/audio/library/paw-prints.wav', style: 'cozy' },
  { key: 'neon-rain', title: 'n e o n r a i n', artist: 'MyPage originals (CC0)', file_path: '/audio/library/neon-rain.wav', style: 'vaporwave' },
  { key: 'under-construction', title: 'Under Construction', artist: 'MyPage originals (CC0)', file_path: '/audio/library/under-construction.wav', style: 'chiptune' },
];

module.exports = {
  TEMPLATES, STICKER_PACKS, CURSOR_PRESETS, MUSIC_LIBRARY,
  builders: { section, text, sticker, widget, doc, framed },
};
