// Product catalog: vibe templates, sticker packs, cursor presets and the
// music-library manifest. Seeded idempotently into the DB at every boot in
// EVERY environment — this is product content, not staging mock data.
// All artwork is original (inline SVG written here); all audio is
// generated by scripts/gen-audio.js (original, CC0).
'use strict';

// ------------------------------------------------------- doc builders

function section(id, background, minHeight, blocks) {
  return { id, background, minHeight, blocks };
}
function text(id, x, y, w, rotation, z, props) {
  return {
    id, type: 'text', x, y, w, rotation, z,
    props: Object.assign(
      { text: '', font: 'inter', size: 20, color: '#1F2B47', bold: false, align: 'left', style: 'none' },
      props
    ),
  };
}
function sticker(id, x, y, w, rotation, z, key) {
  return { id, type: 'sticker', x, y, w, rotation, z, props: { key } };
}
function widget(id, x, y, w, rotation, z, props) {
  return { id, type: 'widget', x, y, w, rotation, z, props };
}
function doc(cursor, song, footerStyle, sections) {
  return { version: 1, cursor, song, footerStyle, sections };
}

// ------------------------------------------------------- vibe templates

const TEMPLATES = [
  {
    key: 'y2k', name: 'Y2K glitter', description: 'hot pink, sparkle text, everything shiny',
    content: doc({ type: 'preset', key: 'heart-wand' }, null, { bg: '#FF9DE2', color: '#2A1F3D' }, [
      section('s1', { type: 'gradient', from: '#FF9DE2', to: '#8A6FDF', angle: 150 }, 520, [
        text('t1', 6, 44, 88, -3, 3, { text: '☆ ur page here ☆', font: 'fraunces', size: 40, color: '#FFFFFF', bold: true, style: 'sparkle' }),
        widget('m1', 4, 170, 92, 0, 2, { kind: 'marquee', text: '♡ welcome 2 my corner ♡ sign the guestbook ♡', speed: 10, color: '#FFE93F', size: 20 }),
        sticker('st1', 74, 250, 18, 14, 4, 'blink-star'),
        widget('w1', 10, 300, 60, -2, 2, { kind: 'mood', mood: '💅', label: 'iconic' }),
        sticker('st2', 6, 380, 15, -10, 4, 'blink-heart'),
      ]),
      section('s2', { type: 'pattern', pattern: 'checker', color: '#FFD9F2', ink: '#FF9DE2' }, 420, [
        text('t2', 8, 40, 80, 1, 2, { text: 'about me\n(everything, all at once)', font: 'comic', size: 24, color: '#B03A7C', bold: true }),
        widget('w2', 10, 190, 78, 0, 2, { kind: 'counter', style: 'pink' }),
        widget('w3', 8, 300, 84, 0, 1, { kind: 'guestbook' }),
      ]),
    ]),
  },
  {
    key: 'scene2007', name: '2007 scene', description: 'dark checkers, rainbow text, rawr',
    content: doc({ type: 'preset', key: 'tiny-sword' }, null, { bg: '#101014', color: '#E8DCFF' }, [
      section('s1', { type: 'pattern', pattern: 'checker', color: '#121218', ink: '#232330' }, 540, [
        text('t1', 6, 44, 88, -4, 3, { text: 'xX_yourname_Xx', font: 'comic', size: 38, color: '#FF5ECB', bold: true, style: 'rainbow' }),
        widget('m1', 4, 168, 92, 0, 2, { kind: 'marquee', text: '~*~ rawr means i love u in dinosaur ~*~', speed: 8, color: '#7CFCD0', size: 18 }),
        sticker('st1', 76, 240, 16, 12, 4, 'blink-bolt'),
        text('t2', 10, 310, 70, 2, 2, { text: 'music is my life.\nthe scene is not dead.', font: 'typewriter', size: 18, color: '#9DB4CC' }),
      ]),
      section('s2', { type: 'solid', color: '#0C0C10' }, 420, [
        widget('w1', 10, 50, 80, 0, 2, { kind: 'links', links: [{ label: 'my band', url: 'https://example.com' }, { label: 'art blog', url: 'https://example.com' }] }),
        widget('w2', 8, 280, 84, 0, 1, { kind: 'guestbook' }),
      ]),
    ]),
  },
  {
    key: 'cottagecore', name: 'cottagecore', description: 'soft paper, pressed flowers, a warm kettle',
    content: doc({ type: 'preset', key: 'paw-prints' }, null, { bg: '#F3EDDF', color: '#5A6378' }, [
      section('s1', { type: 'pattern', pattern: 'dots', color: '#F6F1E3', ink: '#DCE7D2' }, 520, [
        text('t1', 8, 48, 84, -2, 3, { text: 'a soft little corner', font: 'hand', size: 42, color: '#6B7B4E', bold: false }),
        sticker('st1', 72, 150, 18, 8, 4, 'stamp-mushroom'),
        text('t2', 10, 220, 66, 1, 2, { text: 'tea steeping · bread rising ·\nnowhere to be', font: 'typewriter', size: 17, color: '#8A5A2B' }),
        widget('w1', 10, 360, 70, -1, 2, { kind: 'currently', items: [{ verb: 'reading', what: 'a battered paperback' }, { verb: 'growing', what: 'basil, hopefully' }] }),
      ]),
      section('s2', { type: 'gradient', from: '#EFE9D8', to: '#DCE7D2', angle: 180 }, 380, [
        sticker('st2', 8, 60, 16, -6, 3, 'stamp-flower'),
        text('t3', 30, 90, 58, 0, 2, { text: '“the ordinary devotions are enough.”', font: 'fraunces', size: 20, color: '#5A6378' }),
        widget('w2', 10, 240, 78, 0, 1, { kind: 'counter', style: 'classic' }),
      ]),
    ]),
  },
  {
    key: 'dreamcore', name: 'dreamcore', description: 'somewhere you half-remember',
    content: doc({ type: 'preset', key: 'ghost' }, null, { bg: '#1A1430', color: '#B3A6E8' }, [
      section('s1', { type: 'gradient', from: '#1A1430', to: '#2E5B6E', angle: 200 }, 560, [
        text('t1', 8, 60, 84, -1, 3, { text: 'you have been here before', font: 'inter', size: 32, color: '#CFF6FF', bold: true, style: 'outline' }),
        widget('m1', 4, 200, 92, 0, 2, { kind: 'marquee', text: 'the pool is closed · the hallway hums · it is always 3pm', speed: 16, color: '#8A6FDF', size: 16 }),
        widget('w1', 14, 300, 56, 2, 2, { kind: 'mood', mood: '🌙', label: 'liminal' }),
        sticker('st1', 70, 400, 18, -8, 3, 'blink-moon'),
      ]),
      section('s2', { type: 'solid', color: '#121022' }, 380, [
        text('t2', 12, 70, 70, 0, 2, { text: 'leave a note.\nprove you were real.', font: 'typewriter', size: 17, color: '#8FA6B8' }),
        widget('w2', 8, 200, 84, 0, 1, { kind: 'guestbook' }),
      ]),
    ]),
  },
  {
    key: 'vaporwave', name: 'vaporwave', description: 'sunset gradients, pixel serif, checkerboard floors',
    content: doc({ type: 'preset', key: 'hourglass' }, { title: 'n e o n r a i n', artist: 'MyPage originals', linkUrl: null, source: 'library:neon-rain' }, { bg: '#2A1F3D', color: '#FF9DE2' }, [
      section('s1', { type: 'gradient', from: '#FF6B57', to: '#8A6FDF', angle: 180 }, 540, [
        text('t1', 6, 50, 88, 0, 3, { text: 'ＡＥＳＴＨＥＴＩＣ', font: 'pixel', size: 26, color: '#FFFFFF', style: 'shadow' }),
        widget('sg1', 10, 170, 80, -2, 3, { kind: 'song' }),
        sticker('st1', 72, 330, 18, 10, 3, 'stamp-planet'),
        text('t2', 10, 400, 70, 0, 2, { text: 'mall fountains · dial tones · forever dusk', font: 'inter', size: 15, color: '#FFD9F2' }),
      ]),
      section('s2', { type: 'pattern', pattern: 'checker', color: '#2A1F3D', ink: '#3D2E58' }, 360, [
        widget('w1', 12, 60, 74, 0, 2, { kind: 'counter', style: 'terminal' }),
        widget('w2', 8, 190, 84, 0, 1, { kind: 'guestbook' }),
      ]),
    ]),
  },
  {
    key: 'scrapbook', name: 'scrapbook / journal', description: 'taped corners, typewriter notes, hoarded scraps',
    content: doc({ type: 'preset', key: 'sparkle-wand' }, null, { bg: '#FAF6EE', color: '#8A5A2B' }, [
      section('s1', { type: 'solid', color: '#FAF6EE' }, 560, [
        text('t1', 8, 44, 80, -2, 3, { text: 'things i am keeping', font: 'fraunces', size: 34, color: '#1F2B47', bold: true }),
        text('t2', 12, 150, 62, 3, 2, { text: '“Tell me, what is it you plan to do\nwith your one wild and precious life?”', font: 'typewriter', size: 16, color: '#5A6378' }),
        sticker('st1', 70, 130, 20, -7, 4, 'stamp-heart'),
        text('t3', 16, 300, 58, -4, 2, { text: 'ticket stubs · pressed leaves ·\nthe good kind of quiet', font: 'hand', size: 24, color: '#B03A7C' }),
        sticker('st2', 8, 420, 15, 9, 3, 'stamp-strawberry'),
      ]),
      section('s2', { type: 'pattern', pattern: 'grid', color: '#FFFDF4', ink: '#F0E6C8' }, 380, [
        widget('w1', 10, 50, 76, -1, 2, { kind: 'currently', items: [{ verb: 'reading', what: '…' }, { verb: 'watching', what: '…' }, { verb: 'playing', what: '…' }] }),
        widget('w2', 12, 260, 70, 0, 1, { kind: 'counter', style: 'classic' }),
      ]),
    ]),
  },
  {
    key: 'terminal', name: 'brutalist terminal', description: 'green phosphor, no decoration except the decoration',
    content: doc({ type: 'preset', key: 'pixel-arrow' }, null, { bg: '#0A0F0A', color: '#57D93E' }, [
      section('s1', { type: 'pattern', pattern: 'grid', color: '#0A0F0A', ink: '#12240F' }, 540, [
        text('t1', 6, 44, 88, 0, 3, { text: '> whoami', font: 'pixel', size: 20, color: '#57D93E' }),
        text('t2', 6, 130, 88, 0, 2, { text: 'guest@mypage:~$ a page.\nno tracking. no feed. no ads.\njust bytes arranged with intent.', font: 'typewriter', size: 16, color: '#9FE8D2' }),
        widget('w1', 6, 320, 80, 0, 2, { kind: 'links', links: [{ label: '~/projects', url: 'https://example.com' }, { label: '~/writing', url: 'https://example.com' }] }),
      ]),
      section('s2', { type: 'solid', color: '#060906' }, 340, [
        widget('w2', 8, 50, 76, 0, 2, { kind: 'counter', style: 'terminal' }),
        widget('w3', 6, 180, 88, 0, 1, { kind: 'guestbook' }),
      ]),
    ]),
  },
  {
    key: 'construction', name: 'under construction', description: 'the eternal retro-web promise',
    content: doc({ type: 'preset', key: 'hourglass' }, null, { bg: '#FFE93F', color: '#1F2B47' }, [
      section('s1', { type: 'pattern', pattern: 'stripes', color: '#FFE93F', ink: '#1F2B47', angle: 45 }, 520, [
        text('t1', 8, 50, 84, -2, 3, { text: '🚧 UNDER CONSTRUCTION 🚧', font: 'pixel', size: 20, color: '#1F2B47', bold: true }),
        widget('m1', 4, 160, 92, 0, 2, { kind: 'marquee', text: 'pardon our dust — this page is forever becoming', speed: 9, color: '#1F2B47', size: 18 }),
        sticker('st1', 12, 260, 34, -4, 3, 'badge-construction'),
        sticker('st2', 54, 300, 34, 5, 3, 'badge-new'),
      ]),
      section('s2', { type: 'solid', color: '#FFFDF4' }, 400, [
        sticker('st3', 8, 50, 34, -3, 3, 'badge-noalgo'),
        sticker('st4', 52, 80, 34, 4, 3, 'badge-heart'),
        widget('w1', 12, 200, 70, 0, 2, { kind: 'counter', style: 'classic' }),
        widget('w2', 8, 320, 84, 0, 1, { kind: 'guestbook' }),
      ]),
    ]),
  },
];

// ------------------------------------------------------- sticker packs

// Original inline SVGs. Square packs use viewBox 0 0 100 100; badges use
// the classic 88×31 web-button proportions (0 0 176 62).
const s = (body, vb = '0 0 100 100') => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb}">${body}</svg>`;
const STAMP_FRAME = '<rect x="4" y="4" width="92" height="92" fill="#FFFDF4" stroke="#D6C9A8" stroke-width="3" stroke-dasharray="7 5"/>';
const BADGE = (bg, stroke) => `<rect x="2" y="2" width="172" height="58" rx="6" fill="${bg}" stroke="${stroke}" stroke-width="4"/>`;

const STICKER_PACKS = [
  {
    key: 'blinkies', name: 'blinkies',
    stickers: [
      { key: 'blink-star', svg: s('<path d="M50 6 61 38 95 38 68 58 78 92 50 71 22 92 32 58 5 38 39 38Z" fill="#FFE93F" stroke="#C9A227" stroke-width="4"/><circle cx="50" cy="50" r="7" fill="#FFFDF4"/>') },
      { key: 'blink-heart', svg: s('<path d="M50 88 14 52C2 40 6 18 24 14c12-3 22 4 26 12 4-8 14-15 26-12 18 4 22 26 10 38Z" fill="#FF5ECB" stroke="#B03A7C" stroke-width="4"/><circle cx="36" cy="34" r="6" fill="#FFD9F2"/>') },
      { key: 'blink-moon', svg: s('<path d="M66 8A44 44 0 1 0 92 66 36 36 0 0 1 66 8Z" fill="#B3A6E8" stroke="#8A6FDF" stroke-width="4"/><circle cx="30" cy="30" r="4" fill="#FFFDF4"/><circle cx="20" cy="52" r="3" fill="#FFFDF4"/>') },
      { key: 'blink-bolt', svg: s('<path d="M58 4 20 56h20L42 96 80 42H58Z" fill="#7CFCD0" stroke="#2E9E8F" stroke-width="4"/>') },
      { key: 'blink-flower', svg: s('<g fill="#FF9DE2" stroke="#B03A7C" stroke-width="3"><circle cx="50" cy="22" r="15"/><circle cx="78" cy="42" r="15"/><circle cx="67" cy="74" r="15"/><circle cx="33" cy="74" r="15"/><circle cx="22" cy="42" r="15"/></g><circle cx="50" cy="50" r="14" fill="#FFE93F" stroke="#C9A227" stroke-width="3"/>') },
      { key: 'blink-butterfly', svg: s('<g stroke="#8A6FDF" stroke-width="3"><path d="M50 50C20 10 4 24 12 44c6 14 26 16 38 6Z" fill="#B3A6E8"/><path d="M50 50c30-40 46-26 38-6-6 14-26 16-38 6Z" fill="#B3A6E8"/><path d="M50 52C22 88 6 76 14 58c6-12 24-14 36-6Z" fill="#FF9DE2"/><path d="M50 52c28 36 44 24 36 6-6-12-24-14-36-6Z" fill="#FF9DE2"/></g><rect x="46" y="30" width="8" height="42" rx="4" fill="#2A1F3D"/>') },
    ],
  },
  {
    key: 'stamps', name: 'stamps',
    stickers: [
      { key: 'stamp-heart', svg: s(STAMP_FRAME + '<path d="M50 76 26 52c-8-8-5-22 7-25 8-2 14 3 17 8 3-5 9-10 17-8 12 3 15 17 7 25Z" fill="#D65A9E"/>') },
      { key: 'stamp-mushroom', svg: s(STAMP_FRAME + '<path d="M20 50c0-20 14-32 30-32s30 12 30 32Z" fill="#FF6B57"/><circle cx="36" cy="34" r="5" fill="#FFFDF4"/><circle cx="58" cy="28" r="4" fill="#FFFDF4"/><rect x="40" y="50" width="20" height="28" rx="8" fill="#F3EDDF" stroke="#D6C9A8" stroke-width="2"/>') },
      { key: 'stamp-cat', svg: s(STAMP_FRAME + '<path d="M28 40 24 20l14 8Zm44 0 4-20-14 8Z" fill="#8A5A2B"/><circle cx="50" cy="52" r="26" fill="#C9A227"/><circle cx="41" cy="47" r="3.5" fill="#1F2B47"/><circle cx="59" cy="47" r="3.5" fill="#1F2B47"/><path d="M44 60q6 6 12 0" stroke="#1F2B47" stroke-width="3" fill="none"/>') },
      { key: 'stamp-planet', svg: s(STAMP_FRAME + '<circle cx="50" cy="50" r="22" fill="#8A6FDF"/><ellipse cx="50" cy="52" rx="38" ry="10" fill="none" stroke="#FF9DE2" stroke-width="4"/><circle cx="42" cy="43" r="5" fill="#B3A6E8"/>') },
      { key: 'stamp-flower', svg: s(STAMP_FRAME + '<g fill="#7FB542"><rect x="47" y="54" width="6" height="26"/></g><g fill="#FF9DE2" stroke="#B03A7C" stroke-width="2"><circle cx="50" cy="26" r="9"/><circle cx="66" cy="36" r="9"/><circle cx="62" cy="52" r="9"/><circle cx="38" cy="52" r="9"/><circle cx="34" cy="36" r="9"/></g><circle cx="50" cy="40" r="8" fill="#FFE93F"/>') },
      { key: 'stamp-strawberry', svg: s(STAMP_FRAME + '<path d="M50 82C30 70 24 52 30 40c6-10 34-10 40 0 6 12 0 30-20 42Z" fill="#FF6B57"/><path d="M38 32c4-8 20-8 24 0l-12 8Z" fill="#7FB542"/><g fill="#FFFDF4"><circle cx="42" cy="50" r="2"/><circle cx="56" cy="48" r="2"/><circle cx="50" cy="62" r="2"/></g>') },
    ],
  },
  {
    key: 'badges', name: 'retro-web badges',
    stickers: [
      { key: 'badge-new', svg: s(BADGE('#1F2B47', '#FFE93F') + '<text x="88" y="42" font-family="monospace" font-size="30" font-weight="bold" fill="#FFE93F" text-anchor="middle">NEW!!</text>', '0 0 176 62') },
      { key: 'badge-construction', svg: s(BADGE('#FFE93F', '#1F2B47') + '<text x="88" y="27" font-family="monospace" font-size="16" font-weight="bold" fill="#1F2B47" text-anchor="middle">🚧 UNDER</text><text x="88" y="49" font-family="monospace" font-size="16" font-weight="bold" fill="#1F2B47" text-anchor="middle">CONSTRUCTION</text>', '0 0 176 62') },
      { key: 'badge-noalgo', svg: s(BADGE('#0A0F0A', '#57D93E') + '<text x="88" y="27" font-family="monospace" font-size="15" fill="#57D93E" text-anchor="middle">100% ALGORITHM</text><text x="88" y="49" font-family="monospace" font-size="15" fill="#57D93E" text-anchor="middle">FREE ZONE</text>', '0 0 176 62') },
      { key: 'badge-heart', svg: s(BADGE('#FFD9F2', '#D65A9E') + '<text x="88" y="40" font-family="monospace" font-size="18" font-weight="bold" fill="#B03A7C" text-anchor="middle">made with ♥</text>', '0 0 176 62') },
      { key: 'badge-guestbook', svg: s(BADGE('#2A1F3D', '#B3A6E8') + '<text x="88" y="40" font-family="monospace" font-size="16" font-weight="bold" fill="#B3A6E8" text-anchor="middle">SIGN MY BOOK</text>', '0 0 176 62') },
      { key: 'badge-bestviewed', svg: s(BADGE('#F3EDDF', '#8A5A2B') + '<text x="88" y="27" font-family="monospace" font-size="14" fill="#8A5A2B" text-anchor="middle">best viewed</text><text x="88" y="49" font-family="monospace" font-size="14" fill="#8A5A2B" text-anchor="middle">curled up in bed</text>', '0 0 176 62') },
    ],
  },
];

// ------------------------------------------------------- cursor presets

const CURSOR_PRESETS = [
  { key: 'sparkle-wand', name: 'sparkle wand', config: { emoji: '✨', trail: 'sparkle' } },
  { key: 'tiny-sword', name: 'tiny sword', config: { emoji: '🗡️', trail: null } },
  { key: 'paw-prints', name: 'paw prints', config: { emoji: '🐾', trail: 'paws' } },
  { key: 'heart-wand', name: 'heart wand', config: { emoji: '💖', trail: 'hearts' } },
  { key: 'hourglass', name: 'retro hourglass', config: { emoji: '⌛', trail: null } },
  { key: 'ghost', name: 'little ghost', config: { emoji: '👻', trail: 'sparkle' } },
  { key: 'pixel-arrow', name: 'pixel arrow', config: { emoji: '↖️', trail: null } },
  { key: 'strawberry', name: 'strawberry', config: { emoji: '🍓', trail: null } },
];

// ------------------------------------------------------- music library

const MUSIC_LIBRARY = [
  { key: 'dust-and-sundays', title: 'Dust & Sundays', artist: 'MyPage originals (CC0)', file_path: '/audio/library/dust-and-sundays.wav', style: 'lofi' },
  { key: 'starlight-arcade', title: 'Starlight Arcade', artist: 'MyPage originals (CC0)', file_path: '/audio/library/starlight-arcade.wav', style: 'chiptune' },
  { key: 'cloud-garden', title: 'Cloud Garden', artist: 'MyPage originals (CC0)', file_path: '/audio/library/cloud-garden.wav', style: 'ambient' },
  { key: 'paw-prints', title: 'Paw Prints', artist: 'MyPage originals (CC0)', file_path: '/audio/library/paw-prints.wav', style: 'cozy' },
  { key: 'neon-rain', title: 'n e o n r a i n', artist: 'MyPage originals (CC0)', file_path: '/audio/library/neon-rain.wav', style: 'vaporwave' },
  { key: 'under-construction', title: 'Under Construction', artist: 'MyPage originals (CC0)', file_path: '/audio/library/under-construction.wav', style: 'chiptune' },
];

module.exports = {
  TEMPLATES, STICKER_PACKS, CURSOR_PRESETS, MUSIC_LIBRARY,
  builders: { section, text, sticker, widget, doc },
};
